### ISSUE TITLE
Info to put on website

### ISSUE THREAD

**Issue by almarklein** [euroscipy/www.euroscipy.org#4]
* [x] more info on the venue
* [x] (preliminary) tutorial program
* [x] (preliminary) conference program
* [x] sponsors
* [x] locations of tuts/conf/sprints
* [x] info about sprints
* [ ] how people can apply for financial support
* [x] the members of the organization and committees (about)
* [x] info on what project are sprinting

**Comment by almarklein** [comment]
@pya you might be the one who has the best view of who has what role in the organization. If you give me a quick overview, I can collect who participated in reviews and then compose an about-page.

**Comment by pya** [comment]
That is our current structure (may need to be updated):

1. Local/Catering
Thomas Pohl
Sepideh Alassi
Susanne Greiner

2. Tutorials
Emmanuelle Gouillart

3. Program/Keynotes
Federico Vaggi

4. Communication
Pierre de Buyl

5. Coordination
Mike Müller

6. Accounting
Mike Müller

7. Video recording
Thomas Pohl

8. Sponsoring
Mike Müller

9. Web Site
9.1 Statitic
Pierre de Buyl
Mike Müller
9.2 Tito (registration)
Mike Müller
9.3 PaperCall
Mike Müller

10. Outreach (incl. general advertisement)
Pierre de Buyl

11. Help Desk
Susanne Greiner
Miroslav Šedivý

**Comment by almarklein** [comment]
Here is a snippet of code to query the people who rated submissions:
```py
import requests

token = 'your_papercall_api_token'

# Query all submission ids
all_ids = []
for state in ('submitted', 'accepted', 'rejected', 'waitlist'):
    url = 'https://www.papercall.io/api/v1/submissions?_token=%s&per_page=999&state=%s'
    all = requests.get(url % (token, state)).json()
    all_ids.extend([x['id'] for x in all])


# Collect all reviewers
reviewers = set()
for id in all_ids:
    url = 'https://www.papercall.io/api/v1/submissions/%s/ratings?_token=%s'
    ratings = requests.get(url % (id, token)).json()
    for rating in ratings:
        reviewers.add(rating['user']['name'])

# Print a list
for reviewer in sorted(reviewers):
    print(reviewer)
```

The result:
```
Alexander Hendorf
Almar Klein
Emmanuelle Gouillart
Fabian Pedregosa
Federico Vaggi
Kyle Kastner
Nelle Varoquaux
Nicolas P. Rougier
Pauli Virtanen
Thomas Kluyver
Valerio Maggio
```

**Comment by almarklein** [comment]
I'm running out of time, and since this is not urgent, I leave it to someone else (or me, the week before the conf) to add this to the website.

**Comment by almarklein** [comment]
Do we need to put the sponsors on the website?

**Comment by pya** [comment]
Yes, I am about to prepare a page. So far we Enthought, The PSF, Python Software Verband,  and Python Academy. We can take all the infos and logos  from last years page. @almarklein can you prepare a markdown page? I can add the missing details.
